FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# André Timm

API para a aplicação VUTTR (Very Useful Tools to Remember). A aplicação é um simples repositório para gerenciar ferramentas com seus respectivos nomes, links, descrições e tags.

## Autenticação [/login]

### Login [POST]

+ Request (application/json)
    
        {
            "email" : "email@email.com",
            "password" : "password"
        }
        
+ Response 200 (application/json)

        {
            auth: true, 
            token: "TOKEN"
        }
          

## Ferramentas [/tools]

### Lista todas as Ferramentas [GET /tools{?tag}]

+ Parameters
    - tag : `node` (string, optional) - Filtar pro Tag
            
+ Response 200 (application/json)

        [
          {
            "tags": [
              "node",
              "organizing",
              "webapps",
              "domain",
              "developer",
              "https",
              "proxy"
            ],
            "_id": "5c066b1377b4fe3d78a496ec",
            "title": "hotel",
            "link": "https://github.com/typicode/hotel",
            "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
            "createdAt": "2018-12-04T11:54:59.116Z",
            "__v": 0
          }
        ]

### Criar Ferramenta [POST]

+ Request (application/json)

    + Headers
    
            x-access-token: TOKEN
            
    + Body
        
            {
                "title": "hotel",
                "link": "https://github.com/typicode/hotel",
                "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
                "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
            }

+ Response 201 (application/json)

           {
              "tags": [
                "node",
                "organizing",
                "webapps",
                "domain",
                "developer",
                "https",
                "proxy"
              ],
              "_id": "5c06baba99476f2700d5a266",
              "title": "hotel",
              "link": "https://github.com/typicode/hotel",
              "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
              "createdAt": "2018-12-04T17:34:50.734Z",
              "__v": 0
            }

+ Response 401 (application/json)

            {
                Failed to authenticate token
            }            

### Delete Ferramentas [DELETE /tools/{id}]

+ Request (application/json)

    + Headers
    
            x-access-token: TOKEN
            
+ Response 200 (application/json)

    + Body

            {}  

+ Response 401 (application/json)

            {
                Failed to authenticate token
            }                         
